import time
import json
import builtins
import shlex
import subprocess
from typing import Literal
from langchain_core.messages import HumanMessage, SystemMessage # type: ignore

# My modules
from state import OverallState
from .utils.file_utils import create_dir, docker_dir
from .utils.docker_utils import *
from .utils.llm_utils import invoke_structured

from prompts import (
    SYSTEM_PROMPT,
    CHECK_CONTAINER_PROMPT,
    CHECK_SERVICES_VERSIONS_PROMPT,
    CHECK_NETWORK_PROMPT,
    CHECK_EXPLOIT_SURFACE_PROMPT,
    EVAL_PROBE_RESULTS_PROMPT
)
from configuration import (
    langfuse_handler,
    ContainerLogsAssessment,
    ServiceAssessment,
    NetworkAssessment,
    ExploitSurfaceAssessment
)

def test_code(state: OverallState):
    """The agent tests the docker to check if it work correctly"""
    print("\nTesting code...")
    code_dir_path = docker_dir(state.base_path, state.cve_id, state.web_search_tool)
    logs_dir_path = code_dir_path / "logs"
    log_file = logs_dir_path / f"log{state.stats.test_iteration}.txt"
    final_report_file = logs_dir_path / "final_report.txt"
    if not logs_dir_path.exists():
        create_dir(dir_path=logs_dir_path)

    test_fail_output_string = f"\n\nTest iteration #{state.stats.test_iteration} failed! See 'log{state.stats.test_iteration}.txt' for details."

    code = "This is the Docker code:\n"
    for f in state.code.files:
        code += "-" * 10 + f" {f.location} " + "-" * 10 + f"\n{f.content}\n\n"

    #* IMAGE ASSESSMENT *#
    print("\tLaunching Docker...")
    success, logs = launch_docker(code_dir_path=code_dir_path, log_file=log_file)
    if not success:
        state.stats.image_build_failures += 1
        if state.stats.test_iteration == 0:
            state.stats.starting_image_builds = False
            state.stats.starting_container_runs = False

        test_fail_output_string += f"\n\t- IMAGE BUILDING FAILURE (Manual Check)"
        print(f"{test_fail_output_string}")
        with builtins.open(final_report_file, "a") as f:
            f.write(test_fail_output_string)
        with builtins.open(log_file, "a") as f:
            f.write(test_fail_output_string + "\n")

        truncated_build_log = "\n".join(logs.splitlines()[-150:])
        fail_explanation = "my Docker systems terminates its execution because of an error while building one of its images."
        revision_goal = f"Fix the Docker system by modifying its code, which is reported here:\n\n{code}\n"
        revision_goal += f"To understand what is wrong, analyse the last 150 lines of the logs generated by the 'sudo docker compose up --build --detach' command:\n{truncated_build_log}"
        return {
            "stats": state.stats,
            "fail_explanation": fail_explanation,
            "revision_goal": revision_goal,
            "revision_type": "Image Not Built",
        }
    state.milestones.docker_builds = True
    print("\tImages built! Waiting for containers to setup...")

    #* CONTAINER(s) ASSESSMENT *#
    wait_for_service(code_dir_path=code_dir_path)
    container_ids = get_container_ids(code_dir_path=code_dir_path)
    num_containers = len(container_ids)
    for index, cid in enumerate(container_ids):
        print(f"\tTesting container ({index + 1}/{num_containers})...")
        container_log = get_container_logs(cid=cid, log_file=log_file)
        inspect_container_log = inspect_container(cid=cid, log_file=log_file)

        #* Manual Check *#
        if not inspect_container_log["State"]["Running"] or inspect_container_log["State"]["Status"] != "running":
            state.stats.container_run_failures += 1
            if state.stats.test_iteration == 0:
                state.stats.starting_container_runs = False

            test_fail_output_string += f"\n\t- CONTAINER FAILURE (Manual Check)"
            print(f"{test_fail_output_string}")
            with builtins.open(final_report_file, "a") as f:
                f.write(test_fail_output_string)
            with builtins.open(log_file, "a") as f:
                f.write(test_fail_output_string + "\n")

            fail_explanation = "one of the containers of my Docker system is not running correctly."
            revision_goal = f"Fix the Docker system by modifying its code, which is reported here:\n\n{code}\n"
            revision_goal += f"To understand what is wrong, analyse the output logs of the container:\n{container_log}"
            return {
                "stats": state.stats,
                "fail_explanation": fail_explanation,
                "revision_goal": revision_goal,
                "revision_type": "Container Not Running",
            }

        #* LLM-as-a-Judge Check *#
        query = CHECK_CONTAINER_PROMPT.format(
            container_log=container_log,
            inspect_container_log=inspect_container_log,
        )
        query +="\n<|think|>"

        messages = [SystemMessage(content=SYSTEM_PROMPT), HumanMessage(content=query)]
        result = invoke_structured(state.builder_llm, state.model_name, messages, ContainerLogsAssessment, config={"callbacks": [langfuse_handler]})

        if not result.container_ok:
            state.stats.container_run_failures += 1
            if state.stats.test_iteration == 0:
                state.stats.starting_container_runs = False

            test_fail_output_string += f"\n\t- CONTAINER FAILURE (LLM-as-a-Judge Check): {result.fail_explanation}"
            print(f"{test_fail_output_string}")
            with builtins.open(final_report_file, "a") as f:
                f.write(test_fail_output_string)
            with builtins.open(log_file, "a") as f:
                f.write(test_fail_output_string + "\n")

            revision_goal = f"Fix the Docker system by modifying its code, which is reported here:\n\n{code}\n"

            truncated_log = "\n".join(container_log.splitlines()[-150:])
            revision_goal += f"To understand what is wrong, analyse the last 150 lines of the container logs:\n{truncated_log}\n"
            return {
                "stats": state.stats,
                "fail_explanation": result.fail_explanation,
                "revision_goal": revision_goal,
                "revision_type": "Container Not Running",
            }
    state.milestones.docker_runs = True
    print("\tContainers are running! Checking services and versions...")


    #* LLM-as-a-Judge: SERVICE(s) and VERSION ASSESSMENT *#
    service_list = []
    hard_service_versions = ""
    for service in state.web_search_result.services:
        service_list.append(service.name)
        if service.dependency_type == "HARD":
            hard_service_versions += f"\n\t\t- {service.name}: {service.version}"

    os_packages = [s.name for s in state.web_search_result.services
            if s.dependency_type == "HARD" and getattr(s, "packaging_type", "image") == "os_package"]
    runtime_package_versions = get_runtime_package_versions(container_ids, os_packages, log_file) if os_packages else "N/A (no OS-package HARD services)"


    query = CHECK_SERVICES_VERSIONS_PROMPT.format(
        hard_service_versions=hard_service_versions,
        service_list=service_list,
        code=code,
        runtime_package_versions=runtime_package_versions,
    )
    query +="\n<|think|>"
    messages = [SystemMessage(content=SYSTEM_PROMPT), HumanMessage(content=query)]
    result = invoke_structured(state.builder_llm, state.model_name, messages, ServiceAssessment, config={"callbacks": [langfuse_handler]})

    state.stats.services_ok = result.services_ok

    if not result.services_ok:
        state.stats.docker_misconfigured += 1

        test_fail_output_string += f"\n\t- MISSING SERVICES (LLM-as-a-Judge Check): {result.fail_explanation}"
        print(f"{test_fail_output_string}")
        with builtins.open(final_report_file, "a") as f:
            f.write(test_fail_output_string)
        with builtins.open(log_file, "a") as f:
            f.write(test_fail_output_string + "\n")

        revision_goal = (
            f"Fix the Docker system by modifying its code, which is reported here:\n\n{code}\n"
            f"Ensure that ALL of these required services are present and correctly configured: {service_list}"
        )
        return {
            "stats": state.stats,
            "fail_explanation": result.fail_explanation,
            "revision_goal": revision_goal,
            "revision_type": "Missing Services",
        }

    if not result.code_hard_version:
        state.stats.not_vuln_version_fail += 1

        test_fail_output_string += f"\n\t- NOT VULNERABLE VERSION (LLM-as-a-Judge Check): {result.fail_explanation}"
        print(f"{test_fail_output_string}")
        with builtins.open(final_report_file, "a") as f:
            f.write(test_fail_output_string)
        with builtins.open(log_file, "a") as f:
            f.write(test_fail_output_string + "\n")

        hard_service_versions = ""
        for service in state.web_search_result.services:
            if service.dependency_type == "HARD":
                hard_service_versions += f"\n\t\t- {service.name}: {service.version}"
        revision_goal = f"fix this by modifying the Docker's code, which is reported here:\n\n{code}\nEnsure that the 'HARD' service uses one of the vulnerable versions listed here:{hard_service_versions}"

        return {
            "stats": state.stats,
            "fail_explanation": result.fail_explanation,
            "revision_goal": revision_goal,
            "revision_type": "Not Vulnerable Version",
        }
    state.milestones.code_hard_version = True
    print("\tVulnerable version is used! Checking network setup...")

    container_inspect_logs = "These are the output of the 'docker inspect' command of each Docker Container:\n"
    for cid in container_ids:
        container_inspect_logs += f"{inspect_container(cid=cid, log_file=log_file)}\n\n"

    print("\tRunning active inter-container connectivity scans...")
    network_ok, active_fail_explanation = verify_active_network_reachability(container_ids, log_file, state.classification)

    if not network_ok:
        state.stats.docker_misconfigured += 1

        test_fail_output_string += f"\n\t- WRONG NETWORK SETUP (Active Inter-Container Scan): {active_fail_explanation}"
        print(f"{test_fail_output_string}")
        with builtins.open(final_report_file, "a") as f:
            f.write(test_fail_output_string)
        with builtins.open(log_file, "a") as f:
            f.write(test_fail_output_string + "\n")

        revision_goal = (
            f"Fix the Docker networks or application parameters. Active scanning discovered that "
            f"an internal service is completely unreachable: {active_fail_explanation}. "
            f"Verify that internal application daemons are listening on '0.0.0.0' instead of '127.0.0.1' "
            f"inside their respective containers, and check that names matching services in docker-compose are correct."
        )
        return {
            "stats": state.stats,
            "fail_explanation": active_fail_explanation,
            "revision_goal": revision_goal,
            "revision_type": "Wrong Network Setup",
        }

    query = CHECK_NETWORK_PROMPT.format(
        code=code,
        container_inspect_logs=container_inspect_logs,
    )
    query +="\n<|think|>"
    messages = [SystemMessage(content=SYSTEM_PROMPT), HumanMessage(content=query)]
    result = invoke_structured(state.builder_llm, state.model_name, messages, NetworkAssessment, config={"callbacks": [langfuse_handler]})

    if not result.network_setup:
        state.stats.docker_misconfigured += 1

        test_fail_output_string += f"\n\t- WRONG NETWORK SETUP (LLM-as-a-Judge Check): {result.fail_explanation}"
        print(f"{test_fail_output_string}")
        with builtins.open(final_report_file, "a") as f:
            f.write(test_fail_output_string)

        revision_goal = "fix the Docker system by ensuring its network configuration is setup correctly and that all services are available on their respective default network ports"
        return {
            "stats": state.stats,
            "fail_explanation": result.fail_explanation,
            "revision_goal": revision_goal,
            "revision_type": "Wrong Network Setup",
        }

    state.milestones.network_setup = True
    print(f"\tNetwork setup is ok! Docker is running correctly with {num_containers} containers!")

    print("\tVerifying flag placement...")
    flag_ok, flag_explanation = verify_flag_placement(state.classification, container_ids, log_file)
    if not flag_ok:
        state.stats.docker_misconfigured += 1

        test_fail_output_string += f"\n\t- FLAG NOT PLACED: {flag_explanation}"
        print(f"{test_fail_output_string}")
        with builtins.open(final_report_file, "a") as f:
            f.write(test_fail_output_string)
        with builtins.open(log_file, "a") as f:
            f.write(test_fail_output_string + "\n")

        flag_path = getattr(state.classification, "flag_path", "") if state.classification else ""
        revision_goal = (
            f"The CTF flag was not found at its intended location. {flag_explanation} "
            f"Ensure a file containing EXACTLY 'FLAG{{verified_{state.cve_id}}}' is written at '{flag_path}' "
            f"as the LAST instruction of the relevant container (after all setup/COPY/RUN steps, or as the "
            f"last line of entrypoint.sh before 'exec \"$@\"'), that it is NOT inside a directory declared "
            f"as a Docker volume, and that owner/permissions match the specification. "
            f"Fix by modifying the code, which is reported here:\n\n{code}"
        )
        return {
            "stats": state.stats,
            "fail_explanation": f"Flag placement failed: {flag_explanation}",
            "revision_goal": revision_goal,
            "revision_type": "Flag Not Placed",
        }
    state.milestones.flag_placed = True
    if flag_explanation:
        print(f"\t[i] {flag_explanation}")
    else:
        print("\tFlag placement verified!")

    formatted_code = f"Directory tree:\n{state.code.directory_tree}\n\n"
    for f in state.code.files:
        formatted_code += "-" * 10 + f" {f.location} " + "-" * 10 + f"\n{f.content}\n\n"

    output_string = f"\n\nDocker is running correctly with {num_containers} containers!\n\nThis is the final version of the generated code:\n\n{formatted_code}\n\n"
    with builtins.open(final_report_file, "a") as f:
        f.write(f"{output_string}")
    with builtins.open(log_file, "a") as f:
        f.write(output_string + "\n")

    state.stats.num_containers = num_containers
    return {
        "stats": state.stats,
        "milestones": state.milestones,
    }


def verify_flag_placement(classification, container_ids, log_file):
    if not classification or not getattr(classification, "flag_path", ""):
        return True, "flag verification skipped: no classification / flag_path available"

    flag_path = classification.flag_path
    if not flag_path.startswith("/"):
        return True, f"non-filesystem flag ('{flag_path}'): verification deferred to sanity/red-team"

    any_positive = False
    any_clean_check = False
    for cid in container_ids:
        try:
            res = subprocess.run(
                ["docker", "exec", "-u", "root", cid, "sh", "-c",
                 f"test -f '{flag_path}' && echo __FLAG_FOUND__"],
                capture_output=True, text=True, timeout=10,
            )
        except Exception:
            continue

        # rc 0 -> file exists (marker echoed); rc 1 -> file absent (clean negative);
        # rc 126/127 or errors -> no usable shell in this container (inconclusive).
        if res.returncode in (0, 1):
            any_clean_check = True
            if "__FLAG_FOUND__" in res.stdout:
                any_positive = True
                break

    try:
        with builtins.open(log_file, "a") as f:
            f.write(f"\n\nFlag placement check for '{flag_path}': "
                    f"found={any_positive}, checkable_containers={any_clean_check}\n")
    except Exception:
        pass

    if any_positive:
        return True, ""
    if not any_clean_check:
        return True, (f"flag presence at '{flag_path}' could not be verified "
                      f"(no usable shell in any container): deferred")
    return False, f"Flag file not found at '{flag_path}' in any running container."


 
def _is_loopback_hexip(hexip: str) -> bool:
    hexip = hexip.upper()
    if len(hexip) == 8:            
        return hexip.endswith("7F")
    if len(hexip) == 32:           
        return hexip == "00000000000000000000000001000000"
    return False
 
 
def _analyze_listeners(proc_text: str):
    has_listen = False
    non_loopback = False
    for line in proc_text.splitlines():
        parts = line.split()
        if len(parts) < 4 or ":" not in parts[1]:
            continue
        if parts[3].upper() != "0A":        # 0A = TCP_LISTEN
            continue
        has_listen = True
        hexip = parts[1].split(":")[0]
        if not _is_loopback_hexip(hexip):
            non_loopback = True
    return has_listen, (has_listen and not non_loopback)
 
 
def _read_proc_net_tcp(cid: str):
    
    try:
        res = subprocess.run(
            ["docker", "exec", "-u", "root", cid, "sh", "-c",
             "cat /proc/net/tcp /proc/net/tcp6 2>/dev/null"],
            capture_output=True, text=True, timeout=10,
        )
        if res.returncode != 0 or not res.stdout.strip():
            return None
        return res.stdout
    except Exception:
        return None
 
 
def verify_active_network_reachability(container_ids, log_file, classification=None):
    topo = {}
    for cid in container_ids:
        data = inspect_container(cid=cid, log_file=log_file)
        if isinstance(data, str):
            try:
                data = json.loads(data)
                if isinstance(data, list) and data:
                    data = data[0]
            except Exception:
                continue
        name = data.get("Name", cid).lstrip("/")
        nets = set((data.get("NetworkSettings", {}).get("Networks", {}) or {}).keys())
        bindings = data.get("HostConfig", {}).get("PortBindings", {}) or {}
        host_ports = [cp for cp, hl in bindings.items() if hl]
        topo[name] = {"id": cid, "networks": nets, "host_ports": host_ports}
 
    if not topo:
        return False, "No containers could be inspected."
 
    exposed = [n for n, t in topo.items() if t["host_ports"]]
    if not exposed:
        return False, ("No container publishes any host port (HostConfig.PortBindings is "
                       "empty everywhere); the environment is unreachable from the host.")
 
    if len(topo) > 1:
        names = list(topo)
        parent = {n: n for n in names}
 
        def find(x):
            while parent[x] != x:
                parent[x] = parent[parent[x]]
                x = parent[x]
            return x
 
        for i in range(len(names)):
            for j in range(i + 1, len(names)):
                if topo[names[i]]["networks"] & topo[names[j]]["networks"]:
                    parent[find(names[i])] = find(names[j])
 
        groups = {}
        for n in names:
            groups.setdefault(find(n), []).append(n)
        if len(groups) > 1:
            islands = " | ".join(f"[{', '.join(sorted(g))}]" for g in groups.values())
            return False, ("Network isolation detected: containers are split into "
                           f"unreachable groups: {islands}. Attach them to a common "
                           "bridge network in docker-compose.yml.")
 
    if classification is not None and getattr(classification, "requires_secondary_container", False):
        internal = [n for n, t in topo.items() if not t["host_ports"]]
        if not internal:
            return False, ("This CVE requires a hidden internal container, but every "
                           "container publishes a host port. The internal target must "
                           "have NO 'ports' mapping.")
        for n in internal:
            if not any(topo[n]["networks"] & topo[m]["networks"] for m in topo if m != n):
                return False, (f"Internal container '{n}' shares no network with any other "
                               "container, so the SSRF target is unreachable from the bridge.")
 
    for n, t in topo.items():
        proc = _read_proc_net_tcp(t["id"])
        if proc is None:
            continue
        has_listen, all_loopback = _analyze_listeners(proc)
        if has_listen and all_loopback:
            time.sleep(3)
            proc2 = _read_proc_net_tcp(t["id"])
            if proc2 is not None:
                has_listen2, all_loopback2 = _analyze_listeners(proc2)
                if has_listen2 and all_loopback2:
                    return False, (f"Container '{n}' is listening only on loopback "
                                   "(127.0.0.1/::1). Bind the service to 0.0.0.0 so it is "
                                   "reachable across the Docker network.")
 
    return True, ""

def route_test(state: OverallState) -> Literal["Stop Testing", "Revise Code", "Ok"]:
    """Route back to fix the code or stop testing"""
    output_string = "\nRouting test:\n"
    output_string += f"\t- docker_builds={state.milestones.docker_builds}\n"
    output_string += f"\t- docker_runs={state.milestones.docker_runs}\n"
    output_string += f"\t- code_hard_version={state.milestones.code_hard_version}\n"
    output_string += f"\t- network_setup={state.milestones.network_setup}\n"
    output_string += f"\t- flag_placed={state.milestones.flag_placed}\n"
    output_string += f"\t- exploit_surface={state.milestones.exploit_surface_ok}\n"
    output_string += f"\t- test_iteration={state.stats.test_iteration}"
    print(output_string)

    if (state.milestones.docker_builds and state.milestones.docker_runs and
            state.milestones.code_hard_version and state.milestones.network_setup and
            state.milestones.flag_placed and state.milestones.exploit_surface_ok):
        return "Ok"
    elif state.stats.test_iteration + 1 >= 10:
        print("\tMax Iterations Reached!")
        logs_dir_path = docker_dir(state.base_path, state.cve_id, state.web_search_tool) / "logs"
        stats_file = logs_dir_path / "stats.json"
        with builtins.open(stats_file, "w") as f:
            json.dump(state.stats.model_dump(), f, indent=4)

        milestone_file = logs_dir_path / "milestones.json"
        with builtins.open(milestone_file, "w") as f:
            json.dump(state.milestones.model_dump(), f, indent=4)
        with open(state.base_path / "src/docker-agent/results.txt", "a") as f:
            f.write(f"{state.cve_id} | False | False | MaxIter\n")
            f.close()
        return "Stop Testing"
    else:
        return "Revise Code"

def build_host_port_map(container_ids, log_file) -> dict:

    port_map = {}
    for cid in container_ids:
        data = inspect_container(cid=cid, log_file=log_file)
        if isinstance(data, str):
            data = json.loads(data)[0]

        name = data.get("Name", cid).lstrip("/")
        bindings = (
            data.get("HostConfig", {}).get("PortBindings", {}) or {}
        )
        ports = []
        for container_port, host_list in bindings.items():
            if host_list:
                proto = container_port.split("/")[-1]
                for h in host_list:
                    ports.append((h["HostPort"], proto))
        port_map[name] = ports
    return port_map

def test_exploit_surface(state: OverallState):
    if not state.milestones.docker_builds or not state.milestones.docker_runs or not state.milestones.code_hard_version or not state.milestones.network_setup:
        return {"stats": state.stats, "milestones": state.milestones}

    print("\nTesting exploit surface...")
    code_dir_path = docker_dir(state.base_path, state.cve_id, state.web_search_tool)
    logs_dir_path = code_dir_path / "logs"
    log_file = logs_dir_path / f"log{state.stats.test_iteration}.txt"
    final_report_file = logs_dir_path / "final_report.txt"

    container_ids = get_container_ids(code_dir_path=code_dir_path)
    port_map = build_host_port_map(container_ids, log_file)

    code_context = f"Directory tree:\n{state.code.directory_tree}\n\n"
    for f in state.code.files:
        code_context += "-" * 10 + f" {f.location} " + "-" * 10 + f"\n{f.content}\n\n"

    query = CHECK_EXPLOIT_SURFACE_PROMPT.format(
        cve_id=state.cve_id,
        vulnerability_type=state.classification.vulnerability_type if state.classification else "unknown",
        vulnerable_component=state.classification.vulnerable_component if state.classification else "unknown",
        port_map=json.dumps(port_map, indent=2),
    )
    query +="\n<|think|>"
    messages = [
        SystemMessage(content=SYSTEM_PROMPT),
        HumanMessage(content=code_context),
        HumanMessage(content=query),
    ]

    result = invoke_structured(
        state.builder_llm, state.model_name, messages,
        ExploitSurfaceAssessment,
        config={"callbacks": [langfuse_handler]}
    )

    if state.classification.attack_vector == "local":
        result.probes_run.append("sshpass -p 'ctfpass' ssh -o StrictHostKeyChecking=no -p 2222 ctfuser@localhost 'id'")

    probe_results = {}
    failed_probes = []

    for probe_cmd in result.probes_run:
        if not probe_cmd.strip().startswith(("curl", "nc", "wget", "sshpass")):
            probe_results[probe_cmd] = {"stdout": "BLOCKED: Command not permitted.", "returncode": -1}
            failed_probes.append(probe_cmd)
            continue

        try:
            args = shlex.split(probe_cmd)
            res = subprocess.run(args, capture_output=True, text=True, timeout=10)
            probe_results[probe_cmd] = {"stdout": res.stdout[:500], "returncode": res.returncode}
            if res.returncode != 0:
                failed_probes.append(probe_cmd)
        except subprocess.TimeoutExpired:
            probe_results[probe_cmd] = {"stdout": "TIMEOUT", "returncode": -1}
            failed_probes.append(probe_cmd)
        except Exception as e:
            probe_results[probe_cmd] = {"stdout": str(e), "returncode": -1}
            failed_probes.append(probe_cmd)

    if failed_probes:
        time.sleep(15)
        for probe_cmd in failed_probes:
            if probe_results[probe_cmd]["stdout"].startswith("BLOCKED:"):
                continue
            try:
                args = shlex.split(probe_cmd)
                res = subprocess.run(args, capture_output=True, text=True, timeout=10)
                probe_results[probe_cmd] = {"stdout": res.stdout[:500], "returncode": res.returncode}
            except subprocess.TimeoutExpired:
                probe_results[probe_cmd] = {"stdout": "TIMEOUT", "returncode": -1}
            except Exception as e:
                probe_results[probe_cmd] = {"stdout": str(e), "returncode": -1}

    query = EVAL_PROBE_RESULTS_PROMPT.format(
        cve_id=state.cve_id,
        vulnerability_type=state.classification.vulnerability_type if state.classification else "unknown",
        vulnerable_component=state.classification.vulnerable_component if state.classification else "unknown",
        probe_results=json.dumps(probe_results, indent=2),
    )
    query +="\n<|think|>"
    eval_result = invoke_structured(
        state.builder_llm,
        state.model_name,
        [
            SystemMessage(content=SYSTEM_PROMPT),
            HumanMessage(content=query),
        ],
        ExploitSurfaceAssessment,
        config={"callbacks": [langfuse_handler]},
    )

    test_fail_output_string = f"\n\nTest iteration #{state.stats.test_iteration} failed!"

    if not eval_result.surface_ok:
        state.milestones.exploit_surface_ok = False
        state.stats.docker_misconfigured += 1

        test_fail_output_string += f"\n\t- EXPLOIT SURFACE FAILURE: {eval_result.fail_explanation}"
        test_fail_output_string += f"\n\t- COMMANDS ATTEMPTED: {json.dumps(probe_results, indent=2)}"
        print(test_fail_output_string)
        with builtins.open(final_report_file, "a") as f:
            f.write(test_fail_output_string)
        with builtins.open(log_file, "a") as f:
            f.write(test_fail_output_string + "\n")

        return {
            "stats": state.stats,
            "fail_explanation": eval_result.fail_explanation,
            "revision_goal": eval_result.revision_goal,
            "revision_type": "Exploit Surface Not Ready",
        }

    state.milestones.exploit_surface_ok = True
    print("\tExploit surface verified!")
    return {"stats": state.stats, "milestones": state.milestones}